// <auto-generated />
using System;
using JobBoardApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JobBoardApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200921040323_SeedJobBoard")]
    partial class SeedJobBoard
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JobBoardApp.Models.JobBoard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Job")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("BoardGames");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ccbbdb91-713b-4172-b45a-2a07abaf3339"),
                            CreatedAt = new DateTime(2020, 9, 20, 22, 3, 22, 803, DateTimeKind.Local).AddTicks(7738),
                            Description = "Asp C# programming and JavaScript",
                            ExpiresAt = new DateTime(2020, 9, 27, 22, 3, 22, 807, DateTimeKind.Local).AddTicks(8090),
                            Job = "ASP Programmer",
                            JobTitle = "System Engineer"
                        },
                        new
                        {
                            Id = new Guid("2a7d6f50-9c6d-4dbf-a48e-193dab563c77"),
                            CreatedAt = new DateTime(2020, 9, 20, 22, 3, 22, 807, DateTimeKind.Local).AddTicks(8459),
                            Description = "Laravel programming expert",
                            ExpiresAt = new DateTime(2020, 9, 27, 22, 3, 22, 807, DateTimeKind.Local).AddTicks(8468),
                            Job = "PHP Programmer",
                            JobTitle = "System Engineer"
                        },
                        new
                        {
                            Id = new Guid("80c469e8-e547-4391-8e78-1cb6634b931c"),
                            CreatedAt = new DateTime(2020, 9, 20, 22, 3, 22, 807, DateTimeKind.Local).AddTicks(8486),
                            Description = "Django Programming",
                            ExpiresAt = new DateTime(2020, 9, 27, 22, 3, 22, 807, DateTimeKind.Local).AddTicks(8488),
                            Job = "Python Programmer",
                            JobTitle = "System Engineer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
